version: '2'
services:
  consul:
    image: consul:1.0.0
    command: consul agent -dev -client 0.0.0.0
    ports:
      - "8500:8500"
      - "8600:8600/udp"
  customer:
    build: ../microservice-consul-demo/microservice-consul-demo-customer
    links:
     - consul
  catalog:
    build: ../microservice-consul-demo/microservice-consul-demo-catalog
    links:
     - consul
  order:
    build: ../microservice-consul-demo/microservice-consul-demo-order
    links:
     - consul
  apache:
    build: apache
    links:
     - consul
    depends_on:
     - consul
    ports:
     - "8080:80"
  hystrix-dashboard:
    build: ../microservice-consul-demo/microservice-consul-demo-hystrix-dashboard
    links:
     - consul
    ports:
      - "8989:8989"


